from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index$', views.index, name='index'),
    url(r'^start_admin', views.admin, name='start_admin'),
    #url(r'^store_admin', views.store_admin, name='store_admin'),
    url(r'^store_admin_blog', views.store_admin_blog, name='store_admin_blog'),
    #url(r'^script', views.script, name='script'),
    url(r'^login_view$', views.login_view, name='login_view'),
    url(r'^login_process$', views.login_process, name='login_process'),
    url(r'^logout$', views.logout_process, name='logout_process'),
    url(r'^change_lang', views.change_lang , name='change_lang'),
    url(r'^contact', views.contact , name='contact'),
    url(r'^register', views.register_process , name='register_process'),
    url(r'^upload_img', views.upload_img, name='upload_img'),
    url(r'^change_admin_blog', views.change_admin_blog, name='change_admin_blog'),
    url(r'^delete_admin_blog', views.delete_admin_blog, name='delete_admin_blog'),
    url(r'^store_admin_inst', views.store_admin_inst, name='store_admin_inst'),
    url(r'^delete_admin_inst', views.delete_admin_inst, name='delete_admin_inst'),
    url(r'^change_admin_inst', views.change_admin_inst, name='change_admin_inst'),
    url(r'^store_admin_proj', views.store_admin_inst_proj, name='store_admin_inst_proj'),
    url(r'^change_admin_proj', views.change_admin_inst_proj, name='change_admin_inst_proj'),
    url(r'^change_admin_pr_inst_selection', views.change_admin_inst_proj_selection, name='change_admin_inst_proj_selection'),
    url(r'^inst_detail', views.inst_detail , name='inst_detail'),
    url(r'^store_admin_article', views.store_admin_article , name='store_admin_article'),
    url(r'^home_article_details', views.home_article_details , name='home_article_details'),
    url(r'^store_admin_quote', views.store_admin_quote , name='store_admin_quote'),   
    url(r'^store_admin_video', views.store_admin_video , name='store_admin_video'),
    url(r'^change_admin_article', views.change_admin_article , name='change_admin_article'),
    url(r'^store_admin_doc', views.store_admin_doc , name='store_admin_doc'),
    url(r'^change_admin_quote_selection', views.change_admin_quote_selection , name='change_admin_quote_selection'),
    url(r'^change_admin_doc_selection', views.change_admin_doc_selection , name='change_admin_doc_selection'),
    url(r'^change_admin_video_selection', views.change_admin_video_selection , name='change_admin_video_selection'),
    url(r'^delete_admin_article', views.delete_admin_article , name='delete_admin_article'),
    url(r'^delete_admin_projinst', views.delete_admin_projinst , name='delete_admin_projinst'),
    url(r'^delete_admin_quote', views.delete_admin_quote , name='delete_admin_quote'),
    url(r'^delete_admin_doc', views.delete_admin_doc , name='delete_admin_doc'),  
    url(r'^delete_admin_video', views.delete_admin_video , name='delete_admin_video'),   
    url(r'^get_inst_projects', views.get_inst_projects , name='get_inst_projects'),
    url(r'^get_blog', views.get_blog, name='get_blog'),
    url(r'^store_admin_service', views.store_admin_service, name='store_admin_service'),
    url(r'^change_admin_service_selection', views.change_admin_service_selection, name='change_admin_service_selection'),
    url(r'^delete_admin_service', views.delete_admin_service, name='delete_admin_service'),
    url(r'^blog_all', views.blog_all, name='blog_all'),
]
